version: '3.8'

services:
  aitoearn-web:
    image: next-base-image
    container_name: aitoearn-web
    ports:
      - '3000:3000'
    volumes:
      - ./standalone:/app
    command: node server.js
